### ISSUE TITLE
Runtime issue - ES modules

### ISSUE THREAD

**Issue by 48klocs** [sundevour/destiny2-manifest#3]
I updated `destiny2-manifest` to `2.4.0` and tried running it (it's used in a script in https://github.com/48klocs/dim-wish-list-sources ) - I'm getting some opaque resolution errors.

In my script, I `import D2Manifest from "destiny2-manifest/browser/index";` (like the docs say) and moved from constructing the manifest to setting an API key and `await`ing resolution, then I get the following errors.

```
internal/modules/cjs/loader.js:1216
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\48klocs\Documents\GitHub\dim-wish-list-sources\node-utils\node_modules\destiny2-manifest\browser\index.js
require() of ES modules is not supported.
require() of C:\Users\48klocs\Documents\GitHub\dim-wish-list-sources\node-utils\node_modules\destiny2-manifest\browser\index.js from C:\Users\48klocs\Documents\GitHub\dim-wish-list-sources\node-utils\out\validate-rolls.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\48klocs\Documents\GitHub\dim-wish-list-sources\node-utils\node_modules\destiny2-manifest\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (C:\Users\48klocs\Documents\GitHub\dim-wish-list-sources\node-utils\out\validate-rolls.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by sundevour** [comment]
this is extremely expected because d2-manifest is wholly incompatible between major releases, it's upgraded by several node versions, and it's not even a class anymore, but i will take a look at the stuff i built in the wish list repo
